# Generated by Django 5.1.7 on 2025-03-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_course_userprofile_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='courses',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='matric',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
