# Generated by Django 5.1.7 on 2025-04-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_visitor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('VISITOR', 'Visitor'), ('LECTURER', 'Lecturer')], default='STUDENT', max_length=10),
        ),
    ]
